workflows:
  default-workflow:
    name: Build and test Flutter app
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
